##
## flipperzero-toolchain-windows-tools
##
FROM flipperzero-toolchain-windows-build-base AS flipperzero-toolchain-windows-tools

ADD "https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protobuf-cpp-3.21.7.tar.gz" .
ADD "https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2" .
ADD "https://github.com/libusb/hidapi/archive/refs/tags/hidapi-0.14.0.tar.gz" .

ADD "https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.src.tar.gz" .
ADD "https://github.com/pffang/libiconv-for-Windows/releases/download/1.18/libiconv-for-Windows_prebuilt.zip" .

ADD "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-05-22-13-52/ffmpeg-n7.1.1-17-g24de8a98cf-win64-gpl-7.1.zip" .

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    RUST_VERSION=1.87.0

#
# Unpack && remove archives
#
# [!] savannah.nongnu.org often gives back error 502, which breaks the build. so we take the source from the developer repo.
#

RUN . /toolchain/src/buildvars.sh \
&& echo "[#] create rust environment" \
    && cmd apt-get update \
    && cmd apt-get install -y --no-install-recommends autoconf automake bzip2 default-libmysqlclient-dev dpkg-dev file g++ gcc imagemagick libbz2-dev libc6-dev libcurl4-openssl-dev libdb-dev libevent-dev libffi-dev libgdbm-dev libglib2.0-dev libgmp-dev libjpeg-dev libkrb5-dev liblzma-dev libmagickcore-dev libmagickwand-dev libmaxminddb-dev libncurses5-dev libncursesw5-dev libpng-dev libpq-dev libreadline-dev libsqlite3-dev libssl-dev libtool libwebp-dev libxml2-dev libxslt-dev libyaml-dev make patch unzip xz-utils zlib1g-dev \
    && rustArch="x86_64-unknown-linux-gnu" \
    && cmd wget -q -O rustup-init https://static.rust-lang.org/rustup/archive/1.28.2/${rustArch}/rustup-init \
    && chmod a+x rustup-init \
    && ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --default-host ${rustArch} \
    && cmd rustup --version \
    && cmd cargo --version \
    && cmd rustc --version \
    && rustup target add x86_64-pc-windows-gnu \
&& echo "[#] build tools" \
    && mkdir -p /toolchain/src/src/{protobuf,libusb,hidapi,doxygen,ffmpeg} \
    && mkdir -p $WINDOWS_OUTPUT_ROOT/bin/ \
    && unzip ffmpeg-n7.1.1-17-g24de8a98cf-win64-gpl-7.1.zip -d /toolchain/src/src/ffmpeg/ \
    && cp /toolchain/src/src/ffmpeg/ffmpeg-n7.1.1-17-g24de8a98cf-win64-gpl-7.1/bin/ffmpeg.exe $WINDOWS_OUTPUT_ROOT/bin/ \
    && tar --strip-component=1 -xf protobuf-cpp-3.21.7.tar.gz -C /toolchain/src/src/protobuf \
    && tar --strip-component=1 -xf libusb-1.0.24.tar.bz2 -C /toolchain/src/src/libusb \
    && tar --strip-component=1 -xf hidapi-0.14.0.tar.gz -C /toolchain/src/src/hidapi \
    && tar --strip-component=1 -xf doxygen-1.12.0.src.tar.gz -C /toolchain/src/src/doxygen \
    && unzip libiconv-for-Windows_prebuilt.zip -d /toolchain/src/src/libiconv_winbuild/ \
    && git clone https://github.com/flipperdevices/openocd.git /toolchain/src/src/openocd \
    && cd /toolchain/src/src/openocd \
    && git reset --hard 4b909a31d34167f3ef03ff6f70e6d5b4caa7928a \
    && sed -i 's/https\:\/\/git.savannah.nongnu.org\/git\/git2cl.git/git:\/\/repo.or.cz\/git2cl.git/g' /toolchain/src/src/openocd/.gitmodules \
    && git submodule update --init --recursive \
    && find /toolchain/src/archives/ -type f -delete \
&& echo "[#] build ... " \
    && /toolchain/src/build-windows-flipper-tools.sh protobuf \
    && /toolchain/src/build-windows-flipper-tools.sh libusb \
    && /toolchain/src/build-windows-flipper-tools.sh libhidapi \
    && /toolchain/src/build-windows-flipper-tools.sh openocd \
    && /toolchain/src/build-windows-flipper-tools.sh doxygen \
&& echo "[#] build pngquant " \
    && cmd git clone --recursive https://github.com/kornelski/pngquant.git /toolchain/src/src/pngquant \
    && cmd pushd /toolchain/src/src/pngquant \
    && cmd cargo build --release --target x86_64-pc-windows-gnu \
    && cmd cp /toolchain/src/src/pngquant/target/x86_64-pc-windows-gnu/release/pngquant.exe $WINDOWS_OUTPUT_ROOT/bin/ \
    && popd \
    && . /toolchain/src/buildvars.sh \
&& echo "[#] cleanup ... " \
    && /toolchain/src/build-windows-flipper-tools.sh cleanup \
    && cleanup_after_build
