#!/bin/sh

# unofficial strict mode
set -eu;

# vars
SCRIPT_PATH="$(dirname -- "$(readlink -f -- "$0")")";
LIB_PYTHON_PATH="$(cd "$SCRIPT_PATH/../../python/lib" && pwd)"
LIB_OPENSSL_PATH="$(cd "$SCRIPT_PATH/../../openssl/lib" && pwd)"
PYTHON_CA_CERT_PATH="$LIB_PYTHON_PATH/python3.11/site-packages/certifi";

# run
SSL_CERT_FILE="$PYTHON_CA_CERT_PATH/cacert.pem" LD_LIBRARY_PATH="$LIB_OPENSSL_PATH" "$SCRIPT_PATH/openssl-bin" "$@";
