FROM MacOSVenturaWithBrew AS flipperzero-toolchain-binutils
RUN brew update-reset
RUN brew install gettext texinfo coreutils bison flex m4 xz || true
RUN brew link bison --force
ADD https://developer.arm.com/-/media/Files/downloads/gnu/12.3.rel1/srcrel/arm-gnu-toolchain-src-snapshot-12.3.rel1.tar.xz /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/arm-gnu-toolchain-src-snapshot-12.3.rel1.tar.xz -C /toolchain/src/src/
ADD scripts/build-mac-build-libs.sh /toolchain/src/
RUN bash /toolchain/src/build-mac-build-libs.sh
ADD scripts/build-mac-binutils.sh /toolchain/src/
RUN bash /toolchain/src/build-mac-binutils.sh
