FROM flipperzero-toolchain-mac-binutils AS flipperzero-toolchain-mac-tools

ADD https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protobuf-cpp-3.21.7.tar.gz /toolchain/src/archives/
ADD https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2 /toolchain/src/archives/
ADD https://github.com/libusb/hidapi/archive/refs/tags/hidapi-0.14.0.tar.gz /toolchain/src/archives/
ADD https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.src.tar.gz /toolchain/src/archives/

#https://www.videohelp.com/software/ffmpeg
ADD https://www.videohelp.com/download/ffmpeg-7.1.1-macos64-static.7z /toolchain/src/archives/
ADD https://www.videohelp.com/download/ffmpeg-7.1.1-macosarm-static.zip /toolchain/src/archives/

RUN /bin/zsh -c "cd /toolchain/src/archives \
    && mkdir -p /toolchain/src/src/{protobuf,libusb,hidapi,doxygen,ffmpeg} \
    && mkdir -p /toolchain/mac-x86_64-output-root/bin \
    && mkdir -p /toolchain/mac-arm64-output-root/bin \
    && unzip /toolchain/src/archives/ffmpeg-7.1.1-macosarm-static.zip ffmpeg -d /toolchain/mac-arm64-output-root/bin/ \
    && 7z x ffmpeg-7.1.1-macos64-static.7z ffmpeg -o/toolchain/mac-x86_64-output-root/bin/
    && tar --strip-component=1 -xf protobuf-cpp-3.21.7.tar.gz -C /toolchain/src/src/protobuf \
    && tar --strip-component=1 -xf libusb-1.0.24.tar.bz2 -C /toolchain/src/src/libusb \
    && tar --strip-component=1 -xf hidapi-0.14.0.tar.gz -C /toolchain/src/src/hidapi \
    && tar --strip-component=1 -xf doxygen-1.12.0.src.tar.gz -C /toolchain/src/src/doxygen"

RUN /bin/zsh -c "git clone https://github.com/flipperdevices/openocd.git /toolchain/src/src/openocd \
    && cd /toolchain/src/src/openocd \
    && git reset --hard 4b909a31d34167f3ef03ff6f70e6d5b4caa7928a \
    && sed -i 's/https\:\/\/git.savannah.nongnu.org\/git\/git2cl.git/git:\/\/repo.or.cz\/git2cl.git/g' /toolchain/src/src/openocd/.gitmodules \
    && git submodule update --init --recursive"

RUN /bin/zsh -c "export PATH=\"$(brew --prefix bison)/bin:$PATH\" \
    && /toolchain/src/build-mac-flipper-tools.sh"

RUN /bin/zsh -c "relink.sh /toolchain/mac-x86_64-output-root"
RUN /bin/zsh -c "relink.sh /toolchain/mac-arm64-output-root"
