FROM flipperzero-toolchain-binutils AS flipperzero-toolchain-tools
RUN brew install cmake automake autoconf libtool pkg-config
ADD https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protobuf-cpp-3.21.7.tar.gz /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/protobuf-cpp-3.21.7.tar.gz -C /toolchain/src/src/
RUN mv /toolchain/src/src/protobuf-3.21.7 /toolchain/src/src/protobuf
ADD https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-18.1.8.src.tar.xz /toolchain/src/src/archives/
RUN mkdir -p /toolchain/src/src/llvm
RUN tar -xvf /toolchain/src/src/archives/llvm-18.1.8.src.tar.xz -C /toolchain/src/src/llvm
ADD https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang-18.1.8.src.tar.xz /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/clang-18.1.8.src.tar.xz -C /toolchain/src/src/llvm/llvm-18.1.8.src/tools/
RUN mv /toolchain/src/src/llvm/llvm-18.1.8.src/tools/clang-18.1.8.src /toolchain/src/src/llvm/llvm-18.1.8.src/tools/clang
ADD https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/cmake-18.1.8.src.tar.xz /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/cmake-18.1.8.src.tar.xz -C /toolchain/src/src/llvm/
RUN mv /toolchain/src/src/llvm/cmake-18.1.8.src /toolchain/src/src/llvm/cmake
ADD https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/third-party-18.1.8.src.tar.xz /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/third-party-18.1.8.src.tar.xz -C /toolchain/src/src/llvm/
RUN mv /toolchain/src/src/llvm/third-party-18.1.8.src /toolchain/src/src/llvm/third-party
ADD https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang-tools-extra-18.1.8.src.tar.xz /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/clang-tools-extra-18.1.8.src.tar.xz -C /toolchain/src/src/llvm/
RUN mv /toolchain/src/src/llvm/clang-tools-extra-18.1.8.src /toolchain/src/src/llvm/llvm-18.1.8.src/tools/clang/tools/extra
ADD https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2 /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/libusb-1.0.24.tar.bz2 -C /toolchain/src/src/
RUN mv /toolchain/src/src/libusb-1.0.24 /toolchain/src/src/libusb
ADD https://github.com/libusb/hidapi/archive/refs/tags/hidapi-0.14.0.tar.gz /toolchain/src/src/archives/
RUN tar -xvf /toolchain/src/src/archives/hidapi-0.14.0.tar.gz -C /toolchain/src/src/
RUN mv /toolchain/src/src/hidapi-hidapi-0.14.0 /toolchain/src/src/hidapi

RUN bash -c "git clone https://github.com/flipperdevices/openocd.git /toolchain/src/src/openocd && cd /toolchain/src/src/openocd && git reset --hard 2c984ce7ce8e0c88894d9e40924fe9bcc052878e"

ADD https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.src.tar.gz /toolchain/src/src/archives/
RUN tar -xzf /toolchain/src/src/archives/doxygen-1.12.0.src.tar.gz -C /toolchain/src/src/
RUN mv /toolchain/src/src/doxygen-1.12.0 /toolchain/src/src/doxygen

ADD scripts/build-mac-flipper-tools.sh /toolchain/src/
RUN bash /toolchain/src/build-mac-flipper-tools.sh
ADD scripts/relink.sh /usr/bin/
RUN relink.sh /toolchain/mac-x86_64-output-root
RUN relink.sh /toolchain/mac-arm64-output-root
