#!/bin/sh

# unofficial strict mode
set -eu;

# vars
SCRIPT_PATH="$(dirname -- "$(readlink -f -- "$0")")";
LIB_PROTOBUF_PATH="$(cd "$SCRIPT_PATH/../lib" && pwd)";

# run original gdb with out ncurses lib
LD_LIBRARY_PATH="$LIB_PROTOBUF_PATH" "$SCRIPT_PATH/protoc-bin" "$@"
