#!/bin/sh
# shellcheck disable=SC2048,SC2086

# unofficial strict mode
set -eu;

# vars
SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)"
PY_HOME="$(cd "$SCRIPT_PATH/../python" && pwd)";
LIB_OPENSSL_PATH="$(cd "$SCRIPT_PATH/../openssl/lib" && pwd)"

# run
DYLD_LIBRARY_PATH="$LIB_OPENSSL_PATH" PYTHONHOME="$PY_HOME" "$SCRIPT_PATH/arm-none-eabi-gdb-py-bin" "$@";
