#!/bin/sh
# shellcheck disable=SC2048,SC2086

# unofficial strict mode
set -eu;

# vars
SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)"
TOOLCHAIN_PATH_ABS="$(cd "$SCRIPT_PATH/../" && pwd -P)";
LIB_ZSTD_PATH="$(cd "$TOOLCHAIN_PATH_ABS/zstd/lib" && pwd -P)"

# run
DYLD_LIBRARY_PATH="$LIB_ZSTD_PATH" "$SCRIPT_PATH/arm-none-eabi-lto-dump-bin" "$@";
