#!/bin/sh

# unofficial strict mode
set -eu;

# vars
SCRIPT_PATH="$(dirname -- "$(readlink -f -- "$0")")";
LIB_IMAGE_MAGIC_PATH="$(cd "$SCRIPT_PATH/../imagemagick/lib" && pwd)";
LIB_TOOL_PATH="$(cd "$SCRIPT_PATH/../libtool/lib" && pwd)";

# run ImageMagic convert with out libs
LD_LIBRARY_PATH="$LIB_IMAGE_MAGIC_PATH:$LIB_TOOL_PATH" "$SCRIPT_PATH/magick" convert
