#!/bin/sh

# unofficial strict mode
set -eu;

# vars
SCRIPT_PATH="$(dirname -- "$(readlink -f -- "$0")")";
PY_HOME="$(cd "$SCRIPT_PATH/../python" && pwd)";

# run original gdb with local python
LD_LIBRARY_PATH="$PYTHONHOME="$PY_HOME" $SCRIPT_PATH/arm-none-eabi-gdb-py-bin $*
